### ISSUE TITLE
Is the Clubdam API still working?

### ISSUE THREAD

**Issue by d4n1elchen** [connorworley/karafriends#1102]
Hi, 

I came here from Ongaku discord server.

First of all, thanks for open source this awesome project. I tried to set it up myself and it worked great for Joysond and YouTube. However, the DAM minsei API seem not to work. (the other one for song search worked fine) I wonder if this is a know issue or am I set it up incorrectly. Thanks!

**Comment by connorworley** [comment]
DAM has a blocklist that includes a number of VPN endpoints. You might have
to try a few options to find a working one (DM me on discord @nichi and I
can share what I use)

**Comment by d4n1elchen** [comment]
Thanks for the reply but I am sorry I cannot find your discord ID.

**Comment by d4n1elchen** [comment]
Oh, I am dumb. That @ was linkafied to some random GitHub user

**Comment by d4n1elchen** [comment]
Turns out to be a subscription issue. Thanks for the assistant.
